package com.intentbrowser.app.util

import android.app.NotificationChannel
import android.app.NotificationManager
import android.app.PendingIntent
import android.content.ContentValues
import android.content.Context
import android.content.Intent
import android.net.Uri
import android.os.Build
import android.os.Environment
import android.provider.MediaStore
import android.util.Base64
import android.util.Log
import android.webkit.MimeTypeMap
import androidx.core.app.NotificationCompat
import com.intentbrowser.app.data.AppRepository
import com.intentbrowser.app.data.DownloadEntity
import kotlinx.coroutines.CancellationException
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.Job
import kotlinx.coroutines.SupervisorJob
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.SharingStarted
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.map
import kotlinx.coroutines.flow.stateIn
import kotlinx.coroutines.flow.update
import kotlinx.coroutines.isActive
import kotlinx.coroutines.launch
import okhttp3.OkHttpClient
import okhttp3.Request
import java.io.File
import java.io.IOException
import java.io.OutputStream
import java.io.RandomAccessFile
import kotlin.coroutines.coroutineContext

enum class DownloadState {
    DOWNLOADING, PAUSED, COMPLETED, FAILED, CANCELED
}

data class ActiveDownload(
    val id: Long,
    val title: String,
    val url: String,
    val mimeType: String,
    val state: DownloadState = DownloadState.DOWNLOADING,
    val progress: Int = 0,
    val downloadedBytes: Long = 0,
    val totalBytes: Long = -1,
    val userAgent: String? = null,
    val cookies: String? = null,
    val contentUri: Uri? = null,
    val legacyFile: File? = null
)

class CustomDownloadManager(
    private val context: Context,
    private val repository: AppRepository
) {
    private val _downloads = MutableStateFlow<Map<Long, ActiveDownload>>(emptyMap())
    val downloads: StateFlow<List<ActiveDownload>> = _downloads.map { it.values.toList().sortedByDescending { d -> d.id } }
        .stateIn(CoroutineScope(Dispatchers.Default), SharingStarted.Eagerly, emptyList())

    private val client = OkHttpClient()
    private val scope = CoroutineScope(Dispatchers.IO + SupervisorJob())
    private val jobs = mutableMapOf<Long, Job>()
    private val notificationManager =
        context.getSystemService(Context.NOTIFICATION_SERVICE) as NotificationManager

    init {
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
            notificationManager.createNotificationChannel(
                NotificationChannel("downloads", "Downloads", NotificationManager.IMPORTANCE_LOW)
            )
        }
    }

    fun enqueue(id: Long, title: String, url: String, mimeType: String, userAgent: String?, cookies: String?) {
        val safeTitle = title.ifBlank { "download" }
        _downloads.update {
            it + (id to ActiveDownload(id, safeTitle, url, mimeType, userAgent = userAgent, cookies = cookies))
        }
        scope.launch {
            repository.insertDownload(
                DownloadEntity(id, safeTitle, url, mimeType, System.currentTimeMillis(), "RUNNING", 0)
            )
        }
        _downloads.value[id]?.let { showProgressNotification(it) }
        startJob(id)
    }

    /**
     * Save a blob: download (data URL with base64) fetched through the page.
     * The id is generated by the caller (ViewModel).
     */
    fun enqueueBlob(id: Long, dataUrl: String) {
        scope.launch {
            try {
                val comma = dataUrl.indexOf(',')
                require(comma > 0) { "bad data URL" }
                val meta = dataUrl.substring(5, comma) // after "data:"
                require(dataUrl.substring(0, 5) == "data:") { "not a data URL" }
                val mime = meta.substringBefore(';').ifBlank { "application/octet-stream" }
                val bytes = Base64.decode(dataUrl.substring(comma + 1), Base64.DEFAULT)
                val ext = MimeTypeMap.getSingleton().getExtensionFromMimeType(mime) ?: "bin"
                val title = "download_${System.currentTimeMillis()}.$ext"

                _downloads.update {
                    it + (id to ActiveDownload(id, title, "blob:", mime, state = DownloadState.DOWNLOADING))
                }
                repository.insertDownload(
                    DownloadEntity(id, title, "blob:", mime, System.currentTimeMillis(), "RUNNING", 0)
                )

                if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q) {
                    val uri = writeToMediaStore(title, mime) { out -> out.write(bytes) }
                    _downloads.update { m ->
                        m + (id to m[id]!!.copy(
                            state = DownloadState.COMPLETED, progress = 100,
                            downloadedBytes = bytes.size.toLong(), totalBytes = bytes.size.toLong(),
                            contentUri = uri
                        ))
                    }
                } else {
                    val file = uniqueLegacyFile(title)
                    file.writeBytes(bytes)
                    _downloads.update { m ->
                        m + (id to m[id]!!.copy(
                            state = DownloadState.COMPLETED, progress = 100,
                            downloadedBytes = bytes.size.toLong(), totalBytes = bytes.size.toLong(),
                            legacyFile = file
                        ))
                    }
                }
                repository.updateDownloadProgress(id, 100, "SUCCESSFUL")
                _downloads.value[id]?.let { showCompleteNotification(it) }
            } catch (e: Exception) {
                Log.e("DownloadManager", "Blob save failed", e)
                _downloads.update { it + (id to ActiveDownload(id, "download", "blob:", "", state = DownloadState.FAILED)) }
                repository.updateDownloadProgress(id, 0, "FAILED")
            }
        }
    }

    fun pause(id: Long) {
        jobs[id]?.cancel()
        jobs.remove(id)
        _downloads.update {
            val d = it[id]
            if (d != null && d.state == DownloadState.DOWNLOADING) {
                it + (id to d.copy(state = DownloadState.PAUSED))
            } else it
        }
        notificationManager.cancel(id.toInt())
    }

    fun resume(id: Long) {
        val d = _downloads.value[id] ?: return
        if (d.state != DownloadState.PAUSED && d.state != DownloadState.FAILED) return
        _downloads.update { it + (id to d.copy(state = DownloadState.DOWNLOADING)) }
        startJob(id)
    }

    fun cancel(id: Long) {
        jobs[id]?.cancel()
        jobs.remove(id)
        val dl = _downloads.value[id]
        notificationManager.cancel(id.toInt())
        try {
            dl?.contentUri?.let { context.contentResolver.delete(it, null, null) }
            dl?.legacyFile?.let { if (it.exists()) it.delete() }
            // Legacy .part file
            dl?.let {
                val part = File(
                    Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS),
                    "${it.title}.part"
                )
                if (part.exists()) part.delete()
            }
        } catch (_: Exception) {
        }
        _downloads.update { it - id }
        scope.launch { repository.updateDownloadProgress(id, 0, "CANCELED") }
    }

    fun removeCompleted(id: Long) {
        notificationManager.cancel(id.toInt())
        _downloads.update { it - id }
    }

    // ---------- internals ----------

    private fun startJob(id: Long) {
        val job = scope.launch {
            try {
                val dl = _downloads.value[id] ?: return@launch
                if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q) {
                    downloadViaMediaStore(id, dl)
                } else {
                    @Suppress("DEPRECATION")
                    downloadViaLegacyFile(id, dl)
                }
            } catch (e: CancellationException) {
                // Paused or canceled; state already updated by the caller.
            } catch (e: Exception) {
                Log.e("DownloadManager", "Error downloading", e)
                val dl = _downloads.value[id]
                if (dl != null) {
                    _downloads.update { it + (id to dl.copy(state = DownloadState.FAILED)) }
                }
                repository.updateDownloadProgress(id, 0, "FAILED")
                notificationManager.cancel(id.toInt())
            }
        }
        jobs[id] = job
    }

    /** Android 10+: write through MediaStore (raw file paths are blocked by scoped storage). */
    private suspend fun downloadViaMediaStore(id: Long, dl: ActiveDownload) {
        val resolver = context.contentResolver
        var uri = dl.contentUri
        var downloaded = dl.downloadedBytes
        if (uri == null) {
            val values = ContentValues().apply {
                put(MediaStore.Downloads.DISPLAY_NAME, dl.title)
                put(MediaStore.Downloads.MIME_TYPE, dl.mimeType.ifBlank { "application/octet-stream" })
                put(MediaStore.Downloads.RELATIVE_PATH, Environment.DIRECTORY_DOWNLOADS)
                put(MediaStore.Downloads.IS_PENDING, 1)
            }
            uri = resolver.insert(MediaStore.Downloads.EXTERNAL_CONTENT_URI, values)
                ?: throw IOException("MediaStore insert failed")
            val finalUri = uri
            _downloads.update { it + (id to dl.copy(contentUri = finalUri)) }
        }
        val targetUri = uri

        val requestBuilder = Request.Builder().url(dl.url)
        dl.userAgent?.let { requestBuilder.addHeader("User-Agent", it) }
        dl.cookies?.let { requestBuilder.addHeader("Cookie", it) }
        if (downloaded > 0) requestBuilder.addHeader("Range", "bytes=$downloaded-")

        val response = client.newCall(requestBuilder.build()).execute()
        response.use { resp ->
            if (!resp.isSuccessful) throw IOException("HTTP ${resp.code}")
            val body = resp.body ?: throw IOException("Empty body")
            var total = body.contentLength()
            val resumed = downloaded > 0 && resp.code == 206
            if (resumed) {
                total += downloaded
            } else {
                downloaded = 0 // server ignored Range; restart from scratch
            }
            _downloads.update { m ->
                val cur = m[id]
                if (cur != null) m + (id to cur.copy(totalBytes = total)) else m
            }

            resolver.openOutputStream(targetUri, if (resumed) "wa" else "w")!!.use { out ->
                val input = body.byteStream()
                val buffer = ByteArray(32 * 1024)
                var n = 0
                var current = downloaded
                var lastUi = 0L
                var lastNotif = 0L
                while (coroutineContext.isActive && input.read(buffer).also { n = it } != -1) {
                    out.write(buffer, 0, n)
                    current += n
                    val now = System.currentTimeMillis()
                    if (now - lastUi > 300) {
                        lastUi = now
                        val progress = if (total > 0) ((current.toDouble() / total) * 100).toInt() else 0
                        _downloads.update { m ->
                            val cur = m[id]
                            if (cur != null) {
                                m + (id to cur.copy(progress = progress, downloadedBytes = current))
                            } else m
                        }
                    }
                    if (now - lastNotif > 1000) {
                        lastNotif = now
                        _downloads.value[id]?.let { showProgressNotification(it) }
                    }
                }
                out.flush()
            }

            if (!coroutineContext.isActive) throw CancellationException()

            val doneValues = ContentValues().apply { put(MediaStore.Downloads.IS_PENDING, 0) }
            resolver.update(targetUri, doneValues, null, null)
            _downloads.update { m ->
                val cur = m[id]
                if (cur != null) {
                    m + (id to cur.copy(state = DownloadState.COMPLETED, progress = 100))
                } else m
            }
            repository.updateDownloadProgress(id, 100, "SUCCESSFUL")
            _downloads.value[id]?.let { showCompleteNotification(it) }
        }
    }

    /** Pre-29 fallback: raw file paths still work there. */
    @Suppress("DEPRECATION")
    private suspend fun downloadViaLegacyFile(id: Long, dl: ActiveDownload) {
        val baseDir = Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS)
        if (!baseDir.exists()) baseDir.mkdirs()
        val partFile = dl.legacyFile ?: File(baseDir, "${dl.title}.part").also { f ->
            _downloads.update { it + (id to dl.copy(legacyFile = f)) }
        }
        var downloaded = if (partFile.exists()) partFile.length() else 0L

        val requestBuilder = Request.Builder().url(dl.url)
        dl.userAgent?.let { requestBuilder.addHeader("User-Agent", it) }
        dl.cookies?.let { requestBuilder.addHeader("Cookie", it) }
        if (downloaded > 0) requestBuilder.addHeader("Range", "bytes=$downloaded-")

        val response = client.newCall(requestBuilder.build()).execute()
        response.use { resp ->
            if (!resp.isSuccessful) throw IOException("HTTP ${resp.code}")
            val body = resp.body ?: throw IOException("Empty body")
            var total = body.contentLength()
            if (downloaded > 0 && resp.code == 206) {
                total += downloaded
            } else if (resp.code == 200) {
                if (partFile.exists()) partFile.delete()
                downloaded = 0
            }

            _downloads.update { m ->
                val cur = m[id]
                if (cur != null) m + (id to cur.copy(totalBytes = total)) else m
            }

            RandomAccessFile(partFile, "rw").use { raf ->
                raf.seek(if (resp.code == 206) downloaded else 0)
                val input = body.byteStream()
                val buffer = ByteArray(32 * 1024)
                var n = 0
                var current = raf.length()
                if (resp.code != 206) current = 0
                var lastUi = 0L
                var lastNotif = 0L
                while (coroutineContext.isActive && input.read(buffer).also { n = it } != -1) {
                    raf.write(buffer, 0, n)
                    current += n
                    val now = System.currentTimeMillis()
                    if (now - lastUi > 300) {
                        lastUi = now
                        val progress = if (total > 0) ((current.toDouble() / total) * 100).toInt() else 0
                        _downloads.update { m ->
                            val cur = m[id]
                            if (cur != null) {
                                m + (id to cur.copy(progress = progress, downloadedBytes = current))
                            } else m
                        }
                    }
                    if (now - lastNotif > 1000) {
                        lastNotif = now
                        _downloads.value[id]?.let { showProgressNotification(it) }
                    }
                }
            }

            if (!coroutineContext.isActive) throw CancellationException()

            val finalFile = uniqueLegacyFile(baseDir, dl.title)
            partFile.renameTo(finalFile)
            _downloads.update { m ->
                val cur = m[id]
                if (cur != null) {
                    m + (id to cur.copy(
                        state = DownloadState.COMPLETED, progress = 100,
                        title = finalFile.name, legacyFile = finalFile
                    ))
                } else m
            }
            repository.updateDownloadProgress(id, 100, "SUCCESSFUL")
            _downloads.value[id]?.let { showCompleteNotification(it) }
        }
    }

    private fun writeToMediaStore(
        displayName: String,
        mimeType: String,
        write: (OutputStream) -> Unit
    ): Uri {
        val resolver = context.contentResolver
        val values = ContentValues().apply {
            put(MediaStore.Downloads.DISPLAY_NAME, displayName)
            put(MediaStore.Downloads.MIME_TYPE, mimeType.ifBlank { "application/octet-stream" })
            put(MediaStore.Downloads.RELATIVE_PATH, Environment.DIRECTORY_DOWNLOADS)
            put(MediaStore.Downloads.IS_PENDING, 1)
        }
        val uri = resolver.insert(MediaStore.Downloads.EXTERNAL_CONTENT_URI, values)
            ?: throw IOException("MediaStore insert failed")
        try {
            resolver.openOutputStream(uri, "w")!!.use(write)
            val done = ContentValues().apply { put(MediaStore.Downloads.IS_PENDING, 0) }
            resolver.update(uri, done, null, null)
        } catch (e: Exception) {
            resolver.delete(uri, null, null)
            throw e
        }
        return uri
    }

    @Suppress("DEPRECATION")
    private fun uniqueLegacyFile(title: String): File {
        val baseDir = Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS)
        if (!baseDir.exists()) baseDir.mkdirs()
        return uniqueLegacyFile(baseDir, title)
    }

    private fun uniqueLegacyFile(baseDir: File, fileName: String): File {
        var file = File(baseDir, fileName)
        if (!file.exists()) return file
        val name = file.nameWithoutExtension
        val ext = file.extension
        val dotExt = if (ext.isNotEmpty()) ".$ext" else ""
        var counter = 1
        while (file.exists()) {
            file = File(baseDir, "$name ($counter)$dotExt")
            counter++
        }
        return file
    }

    // ---------- notifications ----------

    private fun showProgressNotification(dl: ActiveDownload) {
        try {
            val builder = NotificationCompat.Builder(context, "downloads")
                .setContentTitle(dl.title)
                .setContentText(if (dl.totalBytes > 0) "${dl.progress}%" else "Downloading…")
                .setSmallIcon(android.R.drawable.stat_sys_download)
                .setProgress(100, dl.progress, dl.totalBytes <= 0)
                .setOngoing(true)
                .setOnlyAlertOnce(true)
            notificationManager.notify(dl.id.toInt(), builder.build())
        } catch (_: Exception) {
        }
    }

    private fun showCompleteNotification(dl: ActiveDownload) {
        try {
            notificationManager.cancel(dl.id.toInt())
            val uri = dl.contentUri
            val builder = NotificationCompat.Builder(context, "downloads")
                .setContentTitle("Download complete")
                .setContentText(dl.title)
                .setSmallIcon(android.R.drawable.stat_sys_download_done)
                .setAutoCancel(true)
            if (uri != null) {
                val open = Intent(Intent.ACTION_VIEW).apply {
                    setDataAndType(uri, dl.mimeType.ifBlank { "*/*" })
                    addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
                }
                val pi = PendingIntent.getActivity(
                    context, dl.id.toInt(), open,
                    PendingIntent.FLAG_IMMUTABLE or PendingIntent.FLAG_UPDATE_CURRENT
                )
                builder.setContentIntent(pi)
            }
            notificationManager.notify(dl.id.toInt(), builder.build())
        } catch (_: Exception) {
        }
    }
}
